name: Update Always Real IP
on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python generate_always_real_ip.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add always_real_ip.conf
          git commit -m "Update always-real-ip config"
          git push